#!/usr/bin/env bash
# deepdive-corenlp-server-url -- Prints CoreNLP HTTP server URL
# $ deepdive corenlp server-url [PORT]
#
# $ export CORENLP_PORT=PORT
# $ deepdive corenlp server-url
##
set -euo pipefail

: ${CORENLP_ANNOTATORS:="
        tokenize
        ssplit
        pos
        ner
        lemma
        depparse
	regexner
    "}

# CoreNLP properties
annotators=( $CORENLP_ANNOTATORS )
corenlp_properties=$(echo '
{ "outputFormat"        : "json"
, "annotators"          : "'"$(IFS=,; echo "${annotators[*]}")"'"
, "tokenize.whitespace" : "false"
, "regexner.ignorecase": "true"
, "includeText":	"true"
}')
# , "tokenize.language"   : "en"
# , "parse.model"         : "edu/stanford/nlp/models/lexparser/frenchFactored.ser.gz"
# , "pos.model"           : "edu/stanford/nlp/models/pos-tagger/french/french.tagger"
# , "depparse.model"      : "edu/stanford/nlp/models/parser/nndep/UD_French.gz"



# print CoreNLP server's endpoint URL
echo "http://prevert.limsi.fr:$CORENLP_PORT/?properties=$(jq -r '@uri' <<<"$corenlp_properties")"
#echo "http://localhost:$CORENLP_PORT/?properties=$(jq -r '@uri' <<<"$corenlp_properties")"
